spring.application.name=video_data_service
server.port=8024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/video_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=396046014

spring.data.redis.database=0
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-wait=-1
spring.data.redis.jedis.pool.max-idle=20
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.timeout=5000

spring.quartz.job-store-type=jdbc
#always represent initial database's quartz sheets.never option used after always option used
spring.quartz.jdbc.initialize-schema=never
#spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=ClusteredScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=100
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=20000
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=10000
spring.quartz.properties.org.quartz.jobStore.useProperties=false
spring.quartz.properties.org.quartz.jobStore.dataSource=quartzDS
spring.quartz.properties.org.quartz.dataSource.quartzDS.provider=hikaricp
spring.quartz.properties.org.quartz.dataSource.quartzDS.driver=${spring.datasource.driver-class-name}
spring.quartz.properties.org.quartz.dataSource.quartzDS.URL=${spring.datasource.url}
spring.quartz.properties.org.quartz.dataSource.quartzDS.user=${spring.datasource.username}
spring.quartz.properties.org.quartz.dataSource.quartzDS.password=${spring.datasource.password}
spring.quartz.properties.org.quartz.dataSource.quartzDS.maxConnections=50

spring.jpa.show-sql=true
#It's available to use create option when first build in local machine,then switch this option to update
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=create
spring.security.user.name=admin
spring.security.user.password=admin

#spring.devtools.restart.enabled=true
#disable hot-update to prevent restart nginx server and redis server!
spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**

server.max-http-request-header-size=3096MB
spring.servlet.multipart.max-file-size=3096MB
spring.servlet.multipart.max-request-size=3096MB
server.tomcat.max-swallow-size=3096MB

jwt.expire_time=3600000
jwt.token_prefix=JwtToken
jwt.user_role_key=user_role
jwt.user_name=user_name
jwt.user_pwd=user_pwd
jwt.user_key=user_key

config.video_url_path_root=http://localhost:8026/videos/
config.image_url_path_root=http://localhost:8026/imgs/
config.video_absolute_path_root=C:/Users/12952/Desktop/video_management_system/backEnd/video_data_service/src/main/resources/static/nginx/html/videos/
config.image_absolute_path_root=C:/Users/12952/Desktop/video_management_system/backEnd/video_data_service/src/main/resources/static/nginx/html/imgs/